#
# Makefile to synthesize the project (this is only a dummy)
#

all:
		@echo "Please use Altera Quartus II to synthesize the project!"

clean:
		mv build/lfsr128.qpf .
		mv build/lfsr128.qsf .
		mv build/lfsr128.qws .
		mv build/lfsr128.srf .
		rm -rf build/*
		mv lfsr128.qpf build
		mv lfsr128.qsf build
		mv lfsr128.qws build
		mv lfsr128.srf build
		rm -f *~
