#
# Makefile to synthesize the project (this is only a dummy)
#

all:
		@echo "Please use Xilinx ISE 14.7 to synthesize the project!"

clean:
		mv build/lfsr128.xise .
		rm -rf build/*
		mv lfsr128.xise build
		rm -f *~
